# Generated by Django 5.2.7 on 2025-10-06 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shelters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('age_years', models.IntegerField(help_text='Edad aproximada en años', verbose_name='Edad (años)')),
                ('age_months', models.IntegerField(default=0, help_text='Meses adicionales', verbose_name='Edad (meses)')),
                ('breed', models.CharField(help_text='Raza o mezcla', max_length=100, verbose_name='Raza')),
                ('size', models.CharField(choices=[('pequeño', 'Pequeño'), ('mediano', 'Mediano'), ('grande', 'Grande')], max_length=20, verbose_name='Tamaño')),
                ('gender', models.CharField(choices=[('macho', 'Macho'), ('hembra', 'Hembra')], max_length=10, verbose_name='Sexo')),
                ('color', models.CharField(max_length=100, verbose_name='Color')),
                ('status', models.CharField(choices=[('disponible', 'Disponible'), ('adoptado', 'Adoptado'), ('reservado', 'Reservado')], default='disponible', max_length=20, verbose_name='Estado')),
                ('vaccinated', models.BooleanField(default=False, verbose_name='Vacunado')),
                ('sterilized', models.BooleanField(default=False, verbose_name='Esterilizado')),
                ('dewormed', models.BooleanField(default=False, verbose_name='Desparasitado')),
                ('special_needs', models.TextField(blank=True, null=True, verbose_name='Necesidades especiales')),
                ('photo_main', models.ImageField(upload_to='dogs/', verbose_name='Foto principal')),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to='dogs/', verbose_name='Foto 1')),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to='dogs/', verbose_name='Foto 2')),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to='dogs/', verbose_name='Foto 3')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Publicado por')),
                ('shelter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dogs', to='shelters.shelter', verbose_name='Refugio')),
            ],
            options={
                'verbose_name': 'Perro',
                'verbose_name_plural': 'Perros',
                'ordering': ['-created_at'],
            },
        ),
    ]
