# Generated by Django 5.2.7 on 2025-10-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='dog',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='dog',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de contacto'),
        ),
        migrations.AddField(
            model_name='dog',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de contacto'),
        ),
        migrations.AddField(
            model_name='dog',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='dog',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud'),
        ),
        migrations.AddField(
            model_name='dog',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado'),
        ),
    ]
